package com.wilutions.jsfs;

/*
 * 
 * THIS FILE HAS BEEN GENERATED BY class byps.gen.j.GenApiDescriptor DO NOT MODIFY.
 */

import byps.*;

public class BApiDescriptor_JSFS { 

	/**
	 * API serialisation version: 1.0.0.0
	 */
	public final static long VERSION = 100000000000000L;
	
	public final static BApiDescriptor instance() {
		return new BApiDescriptor(
			"JSFS",
			"com.wilutions.jsfs",
			VERSION,
			false) // uniqueObjects
			.addRegistry(new BRegistry_JSFS());
	}
	
	
}
