package com.wilutions.jsfs;

/*
 * 
 * THIS FILE HAS BEEN GENERATED BY class byps.gen.j.GenClient DO NOT MODIFY.
 */

import byps.*;

public class BClient_JSFS extends BClient { 

	public static BClient_JSFS createClient(BTransportFactory transportFactory) {
		return new BClient_JSFS(transportFactory);
	}
	
	public static BClient_JSFS createClientR(BTransport transport) {
		return new BClient_JSFS(transport);
	}
	
	protected BClient_JSFS(BTransportFactory transportFactory) {
		super(
			transportFactory.createClientTransport(), 
			transportFactory.createServerR(
				BServer_JSFS.createServerR(transportFactory.createServerTransport())
			)
		);
		dispatcherService = new BStub_DispatcherService(transport);
		fileSystemNotify = new BStub_FileSystemNotify(transport);
		fileSystemService = new BStub_FileSystemService(transport);
	}
	
	public BClient_JSFS addRemote(BSkeleton_DispatcherService remoteSkeleton) throws BException {
		if (serverR == null) throw new BException(BExceptionC.NO_REVERSE_CONNECTIONS, "No reverse connections.");
		serverR.server.addRemote(963182355, remoteSkeleton);
		return this;
	}
	
	public BClient_JSFS addRemote(BSkeleton_FileSystemNotify remoteSkeleton) throws BException {
		if (serverR == null) throw new BException(BExceptionC.NO_REVERSE_CONNECTIONS, "No reverse connections.");
		serverR.server.addRemote(1816639285, remoteSkeleton);
		return this;
	}
	
	public BClient_JSFS addRemote(BSkeleton_FileSystemService remoteSkeleton) throws BException {
		if (serverR == null) throw new BException(BExceptionC.NO_REVERSE_CONNECTIONS, "No reverse connections.");
		serverR.server.addRemote(336045129, remoteSkeleton);
		return this;
	}
	
	protected BClient_JSFS(BTransport transport) {
		super(transport, null);
		dispatcherService = new BStub_DispatcherService(transport);
		fileSystemNotify = new BStub_FileSystemNotify(transport);
		fileSystemService = new BStub_FileSystemService(transport);
	}
	
	@Override
	public BRemote getStub(int remoteId) {
		if (remoteId == 963182355) return dispatcherService;
		if (remoteId == 1816639285) return fileSystemNotify;
		if (remoteId == 336045129) return fileSystemService;
		return null;
	}
	
	public final DispatcherServiceAsync dispatcherService;
	public final FileSystemNotifyAsync fileSystemNotify;
	public final FileSystemServiceAsync fileSystemService;
	
}
