package com.wilutions.jsfs;

/*
 * 
 * THIS FILE HAS BEEN GENERATED BY class byps.gen.j.GenClient DO NOT MODIFY.
 */

import byps.*;

public class BClient_JSFS extends BClient { 

	public static BClient_JSFS createClient(BTransportFactory transportFactory) {
		return new BClient_JSFS(transportFactory);
	}
	
	public static BClient_JSFS createClientR(BTransport transport) {
		return new BClient_JSFS(transport);
	}
	
	public BClient_JSFS addRemote(BSkeleton_DispatcherService remoteSkeleton) throws BException {
		if (serverR == null) throw new BException(BExceptionC.NO_REVERSE_CONNECTIONS, "No reverse connections.");
		serverR.server.addRemote(1153231042, remoteSkeleton);
		return this;
	}
	
	public BClient_JSFS addRemote(BSkeleton_FileSystemNotify remoteSkeleton) throws BException {
		if (serverR == null) throw new BException(BExceptionC.NO_REVERSE_CONNECTIONS, "No reverse connections.");
		serverR.server.addRemote(544795964, remoteSkeleton);
		return this;
	}
	
	public BClient_JSFS addRemote(BSkeleton_FileSystemService remoteSkeleton) throws BException {
		if (serverR == null) throw new BException(BExceptionC.NO_REVERSE_CONNECTIONS, "No reverse connections.");
		serverR.server.addRemote(145996442, remoteSkeleton);
		return this;
	}
	
	public DispatcherServiceAsync getDispatcherService() {
		return dispatcherService;
	}
	public FileSystemNotifyAsync getFileSystemNotify() {
		return fileSystemNotify;
	}
	public FileSystemServiceAsync getFileSystemService() {
		return fileSystemService;
	}
	
	@Override
	public BRemote getStub(int remoteId) {
		if (remoteId == 1153231042) return dispatcherService;
		if (remoteId == 544795964) return fileSystemNotify;
		if (remoteId == 145996442) return fileSystemService;
		return null;
	}
	
	protected BClient_JSFS(BTransportFactory transportFactory) {
		super(
			transportFactory.createClientTransport(), 
			transportFactory.createServerR(
				BServer_JSFS.createServerR(transportFactory.createServerTransport())
			)
		);
		initStubs(transport);
	}
	
	protected BClient_JSFS(BTransport transport) {
		super(transport, null);
		initStubs(transport);
	}
	
	protected DispatcherServiceAsync dispatcherService;
	protected FileSystemNotifyAsync fileSystemNotify;
	protected FileSystemServiceAsync fileSystemService;
	
	private void initStubs(BTransport transport) {
		dispatcherService = new BStub_DispatcherService(transport);
		fileSystemNotify = new BStub_FileSystemNotify(transport);
		fileSystemService = new BStub_FileSystemService(transport);
	}
	
}
