package com.wilutions.jsfs;

/*
 * 
 * THIS FILE HAS BEEN GENERATED BY class byps.gen.j.GenRegistry DO NOT MODIFY.
 */

import byps.*;

public class BRegistry_JSFS extends BRegistry { 

	public BRegistry_JSFS() {
		super(BBinaryModel.MEDIUM);
	}
	
	private static BRegisteredSerializer[] serializers = new BRegisteredSerializer[] {
		new BRegisteredSerializer(9906860, "com.wilutions.jsfs.BSerializer_9906860"),
		new BRegisteredSerializer(145996442, "com.wilutions.jsfs.BSerializer_145996442"),
		new BRegisteredSerializer(169662220, "com.wilutions.jsfs.BSerializer_169662220"),
		new BRegisteredSerializer(481066845, "com.wilutions.jsfs.BSerializer_481066845"),
		new BRegisteredSerializer(544795964, "com.wilutions.jsfs.BSerializer_544795964"),
		new BRegisteredSerializer(566696346, "com.wilutions.jsfs.BSerializer_566696346"),
		new BRegisteredSerializer(575037953, "com.wilutions.jsfs.BSerializer_575037953"),
		new BRegisteredSerializer(665368294, "com.wilutions.jsfs.BSerializer_665368294"),
		new BRegisteredSerializer(706034600, "com.wilutions.jsfs.BSerializer_706034600"),
		new BRegisteredSerializer(964561591, "com.wilutions.jsfs.BSerializer_964561591"),
		new BRegisteredSerializer(964561595, "com.wilutions.jsfs.BSerializer_964561595"),
		new BRegisteredSerializer(964561600, "com.wilutions.jsfs.BSerializer_964561600"),
		new BRegisteredSerializer(979378962, "com.wilutions.jsfs.BSerializer_979378962"),
		new BRegisteredSerializer(1032737639, "com.wilutions.jsfs.BSerializer_1032737639"),
		new BRegisteredSerializer(1078989294, "com.wilutions.jsfs.BSerializer_1078989294"),
		new BRegisteredSerializer(1090607752, "com.wilutions.jsfs.BSerializer_1090607752"),
		new BRegisteredSerializer(1092766252, "com.wilutions.jsfs.BSerializer_1092766252"),
		new BRegisteredSerializer(1100528120, "com.wilutions.jsfs.BSerializer_1100528120"),
		new BRegisteredSerializer(1124739608, "com.wilutions.jsfs.BSerializer_1124739608"),
		new BRegisteredSerializer(1131301080, "com.wilutions.jsfs.BSerializer_1131301080"),
		new BRegisteredSerializer(1153231042, "com.wilutions.jsfs.BSerializer_1153231042"),
		new BRegisteredSerializer(1274131736, "com.wilutions.jsfs.BSerializer_1274131736"),
		new BRegisteredSerializer(1354059712, "com.wilutions.jsfs.BSerializer_1354059712"),
		new BRegisteredSerializer(1366717454, "com.wilutions.jsfs.BSerializer_1366717454"),
		new BRegisteredSerializer(1439246415, "com.wilutions.jsfs.BSerializer_1439246415"),
		new BRegisteredSerializer(1542825705, "com.wilutions.jsfs.BSerializer_1542825705"),
		new BRegisteredSerializer(1609273478, "com.wilutions.jsfs.BSerializer_1609273478"),
		new BRegisteredSerializer(1614176016, "com.wilutions.jsfs.BSerializer_1614176016"),
		new BRegisteredSerializer(1733426638, "com.wilutions.jsfs.BSerializer_1733426638"),
		new BRegisteredSerializer(1762179110, "com.wilutions.jsfs.BSerializer_1762179110"),
		new BRegisteredSerializer(1815527676, "com.wilutions.jsfs.BSerializer_1815527676"),
		new BRegisteredSerializer(1824869366, "com.wilutions.jsfs.BSerializer_1824869366"),
		new BRegisteredSerializer(1833696176, "com.wilutions.jsfs.BSerializer_1833696176"),
		new BRegisteredSerializer(1849102471, "com.wilutions.jsfs.BSerializer_1849102471"),
		new BRegisteredSerializer(1888107655, "com.wilutions.jsfs.BSerializer_1888107655"),
		new BRegisteredSerializer(1925305675, "com.wilutions.jsfs.BSerializer_1925305675"),
	};
	@Override
	protected BRegisteredSerializer[] getSortedSerializers() {
		return serializers;
	}
}
