package com.wilutions.jsfs;

/*
 * 
 * THIS FILE HAS BEEN GENERATED BY class byps.gen.j.GenApiClass DO NOT MODIFY.
 */

import byps.*;
import java.io.Serializable;

/**
*/
@SuppressWarnings("all")
public final class BRequest_FileSystemService_executeNotifyExit extends BMethodRequest implements Serializable {

	public java.lang.String[] args;
	public ExecuteOptions opts;
	
	public final static long serialVersionUID = 1824869366L;
	
	public int getRemoteId() { return 145996442; }
	
	public void execute(BRemote __byps__remote, BAsyncResult<Object> __byps__asyncResult) throws Throwable {
		try {
			final FileSystemServiceAsync __byps__remoteT = (FileSystemServiceAsync)__byps__remote;			
			BAsyncResultSendMethod<Object> __byps__outerResult = new BAsyncResultSendMethod<Object>(__byps__asyncResult, new BResult_19());			
			__byps__remoteT.executeNotifyExit(args, opts, __byps__outerResult);
		} catch (Throwable e) {
			__byps__asyncResult.setAsyncResult(null, e);
			throw e;
		}
	}	
	
	public String toString() {
		StringBuilder s = new StringBuilder();
		s.append("[FileSystemService.executeNotifyExit(");
		s.append(args);
		s.append(",").append(opts);
		s.append(")]");
		return s.toString();
	}
	
}
