package com.wilutions.jsfs;

/*
 * 
 * THIS FILE HAS BEEN GENERATED BY class byps.gen.j.GenApiClass DO NOT MODIFY.
 */

import byps.*;
import java.io.Serializable;

/**
*/
@SuppressWarnings("all")
public final class BRequest_DispatcherService_getNotifyService extends BMethodRequest implements Serializable {

	public java.lang.String token;
	public boolean onlyHere;
	
	public final static long serialVersionUID = 1090607752L;
	
	public int getRemoteId() { return 1153231042; }
	
	public void execute(BRemote __byps__remote, BAsyncResult<Object> __byps__asyncResult) throws Throwable {
		try {
			final DispatcherServiceAsync __byps__remoteT = (DispatcherServiceAsync)__byps__remote;			
			BAsyncResultSendMethod<FileSystemNotify> __byps__outerResult = new BAsyncResultSendMethod<FileSystemNotify>(__byps__asyncResult, new BResult_1816639285());			
			__byps__remoteT.getNotifyService(token, onlyHere, __byps__outerResult);
		} catch (Throwable e) {
			__byps__asyncResult.setAsyncResult(null, e);
		}
	}	
	
	public String toString() {
		StringBuilder s = new StringBuilder();
		s.append("[DispatcherService.getNotifyService(");
		s.append(token);
		s.append(",").append(onlyHere);
		s.append(")]");
		return s.toString();
	}
	
}
