package com.wilutions.jsfs;

/*
 * 
 * THIS FILE HAS BEEN GENERATED BY class byps.gen.j.GenApiClass DO NOT MODIFY.
 */

import byps.*;
import java.io.Serializable;

/**
*/
@SuppressWarnings("all")
public final class BResult_1439246415 extends BMethodResult<java.util.List<FileInfo>> implements Serializable {

	
	public final static long serialVersionUID = 1733426638L;
	
}
