package com.wilutions.jsfs;

/*
 * 
 * THIS FILE HAS BEEN GENERATED BY class byps.gen.j.GenApiClass DO NOT MODIFY.
 */

import byps.*;
import java.io.Serializable;

/**
*/
@SuppressWarnings("all")
public final class BResult_1816639285 extends BMethodResult<FileSystemNotify> implements Serializable {

	
	public final static long serialVersionUID = 1354059712L;
	
}
