package com.wilutions.jsfs;

/*
 * 
 * THIS FILE HAS BEEN GENERATED BY class byps.gen.j.GenApiClass DO NOT MODIFY.
 */

import byps.*;
import java.io.Serializable;

/**
*/
@SuppressWarnings("all")
public final class BResult_5 extends BMethodResult<Integer> implements Serializable {

	
	public final static long serialVersionUID = 169662220L;
	
}
