package com.wilutions.jsfs;

/*
 * 
 * THIS FILE HAS BEEN GENERATED BY class byps.gen.j.GenApiClass DO NOT MODIFY.
 */

import byps.*;
import java.io.Serializable;

/**
*/
@SuppressWarnings("all")
public final class BResult_10 extends BMethodResult<String> implements Serializable {

	
	public final static long serialVersionUID = 964561600L;
	
}
