package com.wilutions.jsfs;

/*
 * 
 * THIS FILE HAS BEEN GENERATED BY class byps.gen.j.GenApiClass DO NOT MODIFY.
 */

import byps.*;
import java.io.Serializable;

/**
*/
@SuppressWarnings("all")
public final class BResult_15 extends BMethodResult<java.io.InputStream> implements Serializable {

	
	public final static long serialVersionUID = 964561595L;
	
}
