package com.wilutions.jsfs;

/*
 * 
 * THIS FILE HAS BEEN GENERATED BY class byps.gen.j.GenApiClass DO NOT MODIFY.
 */

import byps.*;
import java.io.Serializable;

/**
*/
@SuppressWarnings("all")
public final class BResult_336045129 extends BMethodResult<FileSystemService> implements Serializable {

	
	public final static long serialVersionUID = 1815527676L;
	
}
