package com.wilutions.jsfs;

/*
 * Serializer for com.wilutions.jsfs.BRequest_FileSystemNotify_notify
 * 
 * THIS FILE HAS BEEN GENERATED BY class byps.gen.j.GenSerStruct DO NOT MODIFY.
 */

import byps.*;

// DEBUG
// isEnum=false
// isFinal=true
// isInline=false
// #members=1

// checkpoint byps.gen.j.GenSerStruct:274
@SuppressWarnings("all")
public class BSerializer_481066845 extends BSerializer {
	
	public final static BSerializer instance = new BSerializer_481066845();
	
	public BSerializer_481066845() {
		super(481066845);
	}
	
	public BSerializer_481066845(int typeId) {
		super(typeId);
	}
	
	
	@Override
	public void write(final Object obj1, final BOutput bout1, final long version) throws BException {
		final BRequest_FileSystemNotify_notify obj = (BRequest_FileSystemNotify_notify)obj1;		
		final BOutputBin bout = (BOutputBin)bout1;
		final BBufferBin bbuf = bout.bbuf;
		bout.writeObj(obj.notifyInfo, false, null);
	}
	
	@Override
	public Object read(final Object obj1, final BInput bin1, final long version) throws BException {
		final BInputBin bin = (BInputBin)bin1;
		final BRequest_FileSystemNotify_notify obj = (BRequest_FileSystemNotify_notify)(obj1 != null ? obj1 : bin.onObjectCreated(new BRequest_FileSystemNotify_notify()));
		
		final BBufferBin bbuf = bin.bbuf;
		
		obj.notifyInfo = (com.wilutions.jsfs.NotifyInfo)bin.readObj(false, null);
		
		return obj;
	}
	
}
