package com.wilutions.jsfs;

/*
 * Serializer for com.wilutions.jsfs.BRequest_DispatcherService_registerService
 * 
 * THIS FILE HAS BEEN GENERATED BY class byps.gen.j.GenSerStruct DO NOT MODIFY.
 */

import byps.*;

// DEBUG
// isEnum=false
// isFinal=true
// isInline=false
// #members=2

// checkpoint byps.gen.j.GenSerStruct:274
@SuppressWarnings("all")
public class BSerializer_1833696176 extends BSerializer {
	
	public final static BSerializer instance = new BSerializer_1833696176();
	
	public BSerializer_1833696176() {
		super(1833696176);
	}
	
	public BSerializer_1833696176(int typeId) {
		super(typeId);
	}
	
	
	@Override
	public void write(final Object obj1, final BOutput bout1, final long version) throws BException {
		final BRequest_DispatcherService_registerService obj = (BRequest_DispatcherService_registerService)obj1;		
		final BOutputBin bout = (BOutputBin)bout1;
		final BBufferBin bbuf = bout.bbuf;
		bbuf.putString(obj.token);
		bout.writeObj(obj.service, false, null);
	}
	
	@Override
	public Object read(final Object obj1, final BInput bin1, final long version) throws BException {
		final BInputBin bin = (BInputBin)bin1;
		final BRequest_DispatcherService_registerService obj = (BRequest_DispatcherService_registerService)(obj1 != null ? obj1 : bin.onObjectCreated(new BRequest_DispatcherService_registerService()));
		
		final BBufferBin bbuf = bin.bbuf;
		
		obj.token = bbuf.getString();
		obj.service = (com.wilutions.jsfs.FileSystemService)bin.readObj(false, null);
		
		return obj;
	}
	
}
