package com.wilutions.jsfs;

/*
 * Serializer for com.wilutions.jsfs.ExecuteNotifyInfo
 * 
 * THIS FILE HAS BEEN GENERATED BY class byps.gen.j.GenSerStruct DO NOT MODIFY.
 */

import byps.*;

// DEBUG
// isEnum=false
// isFinal=false
// isInline=false
// #members=3

// checkpoint byps.gen.j.GenSerStruct:274
@SuppressWarnings("all")
public class BSerializer_665368294 extends com.wilutions.jsfs.BSerializer_1274131736 {
	
	public final static BSerializer instance = new BSerializer_665368294();
	
	public BSerializer_665368294() {
		super(665368294);
	}
	
	public BSerializer_665368294(int typeId) {
		super(typeId);
	}
	
	
	@Override
	public void write(final Object obj1, final BOutput bout1, final long version) throws BException {
		final ExecuteNotifyInfo obj = (ExecuteNotifyInfo)obj1;		
		super.write(obj, bout1, version);		
		final BOutputBin bout = (BOutputBin)bout1;
		final BBufferBin bbuf = bout.bbuf;
		bbuf.putInt(obj.exitCode);
		bbuf.putString(obj.standardError);
		bbuf.putString(obj.standardOutput);
	}
	
	@Override
	public Object read(final Object obj1, final BInput bin1, final long version) throws BException {
		final BInputBin bin = (BInputBin)bin1;
		final ExecuteNotifyInfo obj = (ExecuteNotifyInfo)(obj1 != null ? obj1 : bin.onObjectCreated(new ExecuteNotifyInfo()));
		
		// Read base class members
		super.read(obj, bin, version);
		
		final BBufferBin bbuf = bin.bbuf;
		
		obj.exitCode = bbuf.getInt();
		obj.standardError = bbuf.getString();
		obj.standardOutput = bbuf.getString();
		
		return obj;
	}
	
}
