package com.wilutions.jsfs;

/*
 * Serializer for com.wilutions.jsfs.BRequest_FileSystemService_findFiles
 * 
 * THIS FILE HAS BEEN GENERATED BY class byps.gen.j.GenSerStruct DO NOT MODIFY.
 */

import byps.*;

// DEBUG
// isEnum=false
// isFinal=true
// isInline=false
// #members=2

// checkpoint byps.gen.j.GenSerStruct:274
@SuppressWarnings("all")
public class BSerializer_1131301080 extends BSerializer {
	
	public final static BSerializer instance = new BSerializer_1131301080();
	
	public BSerializer_1131301080() {
		super(1131301080);
	}
	
	public BSerializer_1131301080(int typeId) {
		super(typeId);
	}
	
	
	@Override
	public void write(final Object obj1, final BOutput bout1, final long version) throws BException {
		final BRequest_FileSystemService_findFiles obj = (BRequest_FileSystemService_findFiles)obj1;		
		final BOutputBin bout = (BOutputBin)bout1;
		final BBufferBin bbuf = bout.bbuf;
		bbuf.putString(obj.path);
		bout.writeObj(obj.findOptions, false, null);
	}
	
	@Override
	public Object read(final Object obj1, final BInput bin1, final long version) throws BException {
		final BInputBin bin = (BInputBin)bin1;
		final BRequest_FileSystemService_findFiles obj = (BRequest_FileSystemService_findFiles)(obj1 != null ? obj1 : bin.onObjectCreated(new BRequest_FileSystemService_findFiles()));
		
		final BBufferBin bbuf = bin.bbuf;
		
		obj.path = bbuf.getString();
		obj.findOptions = (com.wilutions.jsfs.FindOptions)bin.readObj(false, null);
		
		return obj;
	}
	
}
