package com.wilutions.jsfs;

/*
 * Serializer for java.util.List<com.wilutions.jsfs.FileInfo>
 * 
 * THIS FILE HAS BEEN GENERATED BY class byps.gen.j.GenSerList DO NOT MODIFY.
 */

import byps.*;
import java.util.*;

@SuppressWarnings("all")
public class BSerializer_1439246415 extends BSerializer {
	
	public final static BSerializer instance = new BSerializer_1439246415();
	
	public BSerializer_1439246415() {
		super(1439246415);
	}
	
	public Object read(final Object obj1, final BInput bin1, final long version) throws BException {
		final BInputBin bin = (BInputBin)bin1;
		final BBufferBin bbuf = bin.bbuf;
		final int n = bbuf.getLength();
		final ArrayList<com.wilutions.jsfs.FileInfo> arr = new ArrayList<com.wilutions.jsfs.FileInfo>(n);
		bin.onObjectCreated(arr);
		for (int i0 = 0; i0 < n; i0++) {
			com.wilutions.jsfs.FileInfo obj = (com.wilutions.jsfs.FileInfo)bin.readObj(false, null);
			arr.add(obj);
		}
		return arr;
	}
	
	public void write(Object obj1, BOutput bout1, final long version)  throws BException {
		BOutputBin bout = (BOutputBin)bout1;
		BBufferBin bbuf = bout.bbuf;
		java.util.List<com.wilutions.jsfs.FileInfo> arr = (java.util.List<com.wilutions.jsfs.FileInfo>)obj1;
		int n = arr.size();
		bbuf.putLength(n);
		for (com.wilutions.jsfs.FileInfo obj : arr) {
			// checkpoint byps.gen.j.PrintContext:313
			bout.writeObj(obj, false, null);
		}
	}
	
}
