package com.wilutions.jsfs;

/*
 * Serializer for com.wilutions.jsfs.FindOptions
 * 
 * THIS FILE HAS BEEN GENERATED BY class byps.gen.j.GenSerStruct DO NOT MODIFY.
 */

import byps.*;

// DEBUG
// isEnum=false
// isFinal=false
// isInline=false
// #members=1

// checkpoint byps.gen.j.GenSerStruct:274
@SuppressWarnings("all")
public class BSerializer_1092766252 extends BSerializer {
	
	public final static BSerializer instance = new BSerializer_1092766252();
	
	public BSerializer_1092766252() {
		super(1092766252);
	}
	
	public BSerializer_1092766252(int typeId) {
		super(typeId);
	}
	
	
	@Override
	public void write(final Object obj1, final BOutput bout1, final long version) throws BException {
		final FindOptions obj = (FindOptions)obj1;		
		final BOutputBin bout = (BOutputBin)bout1;
		final BBufferBin bbuf = bout.bbuf;
		bbuf.putString(obj.reserved);
	}
	
	@Override
	public Object read(final Object obj1, final BInput bin1, final long version) throws BException {
		final BInputBin bin = (BInputBin)bin1;
		final FindOptions obj = (FindOptions)(obj1 != null ? obj1 : bin.onObjectCreated(new FindOptions()));
		
		final BBufferBin bbuf = bin.bbuf;
		
		obj.reserved = bbuf.getString();
		
		return obj;
	}
	
}
