package com.wilutions.jsfs;

/*
 * Serializer for com.wilutions.jsfs.BRequest_DispatcherService_getService
 * 
 * THIS FILE HAS BEEN GENERATED BY class byps.gen.j.GenSerStruct DO NOT MODIFY.
 */

import byps.*;

// DEBUG
// isEnum=false
// isFinal=true
// isInline=false
// #members=2

// checkpoint byps.gen.j.GenSerStruct:274
@SuppressWarnings("all")
public class BSerializer_575037953 extends BSerializer {
	
	public final static BSerializer instance = new BSerializer_575037953();
	
	public BSerializer_575037953() {
		super(575037953);
	}
	
	public BSerializer_575037953(int typeId) {
		super(typeId);
	}
	
	
	@Override
	public void write(final Object obj1, final BOutput bout1, final long version) throws BException {
		final BRequest_DispatcherService_getService obj = (BRequest_DispatcherService_getService)obj1;		
		final BOutputBin bout = (BOutputBin)bout1;
		final BBufferBin bbuf = bout.bbuf;
		bbuf.putBoolean(obj.onlyHere);
		bbuf.putString(obj.token);
	}
	
	@Override
	public Object read(final Object obj1, final BInput bin1, final long version) throws BException {
		final BInputBin bin = (BInputBin)bin1;
		final BRequest_DispatcherService_getService obj = (BRequest_DispatcherService_getService)(obj1 != null ? obj1 : bin.onObjectCreated(new BRequest_DispatcherService_getService()));
		
		final BBufferBin bbuf = bin.bbuf;
		
		obj.onlyHere = bbuf.getBoolean();
		obj.token = bbuf.getString();
		
		return obj;
	}
	
}
