package com.wilutions.jsfs;

/*
 * Serializer for com.wilutions.jsfs.BResult_10
 * 
 * THIS FILE HAS BEEN GENERATED BY class byps.gen.j.GenSerStruct DO NOT MODIFY.
 */

import byps.*;

// DEBUG
// isEnum=false
// isFinal=true
// isInline=false
// #members=1

// checkpoint byps.gen.j.GenSerStruct:274
@SuppressWarnings("all")
public class BSerializer_964561600 extends BSerializer {
	
	public final static BSerializer instance = new BSerializer_964561600();
	
	public BSerializer_964561600() {
		super(964561600);
	}
	
	public BSerializer_964561600(int typeId) {
		super(typeId);
	}
	
	
	@Override
	public void write(final Object obj1, final BOutput bout1, final long version) throws BException {
		final BResult_10 obj = (BResult_10)obj1;		
		final BOutputBin bout = (BOutputBin)bout1;
		final BBufferBin bbuf = bout.bbuf;
		bbuf.putString(obj.result);
	}
	
	@Override
	public Object read(final Object obj1, final BInput bin1, final long version) throws BException {
		final BInputBin bin = (BInputBin)bin1;
		final BResult_10 obj = (BResult_10)(obj1 != null ? obj1 : bin.onObjectCreated(new BResult_10()));
		
		final BBufferBin bbuf = bin.bbuf;
		
		obj.result = bbuf.getString();
		
		return obj;
	}
	
}
