package com.wilutions.jsfs;

/*
 * Serializer for com.wilutions.jsfs.BRequest_DispatcherService_getNotifyService
 * 
 * THIS FILE HAS BEEN GENERATED BY class byps.gen.j.GenSerStruct DO NOT MODIFY.
 */

import byps.*;

// DEBUG
// isEnum=false
// isFinal=true
// isInline=false
// #members=2

// checkpoint byps.gen.j.GenSerStruct:274
@SuppressWarnings("all")
public class BSerializer_1090607752 extends BSerializer {
	
	public final static BSerializer instance = new BSerializer_1090607752();
	
	public BSerializer_1090607752() {
		super(1090607752);
	}
	
	public BSerializer_1090607752(int typeId) {
		super(typeId);
	}
	
	
	@Override
	public void write(final Object obj1, final BOutput bout1, final long version) throws BException {
		final BRequest_DispatcherService_getNotifyService obj = (BRequest_DispatcherService_getNotifyService)obj1;		
		final BOutputBin bout = (BOutputBin)bout1;
		final BBufferBin bbuf = bout.bbuf;
		bbuf.putBoolean(obj.onlyHere);
		bbuf.putString(obj.token);
	}
	
	@Override
	public Object read(final Object obj1, final BInput bin1, final long version) throws BException {
		final BInputBin bin = (BInputBin)bin1;
		final BRequest_DispatcherService_getNotifyService obj = (BRequest_DispatcherService_getNotifyService)(obj1 != null ? obj1 : bin.onObjectCreated(new BRequest_DispatcherService_getNotifyService()));
		
		final BBufferBin bbuf = bin.bbuf;
		
		obj.onlyHere = bbuf.getBoolean();
		obj.token = bbuf.getString();
		
		return obj;
	}
	
}
