package com.wilutions.jsfs;

/*
 * Serializer for com.wilutions.jsfs.BRequest_FileSystemService_uploadFile
 * 
 * THIS FILE HAS BEEN GENERATED BY class byps.gen.j.GenSerStruct DO NOT MODIFY.
 */

import byps.*;

// DEBUG
// isEnum=false
// isFinal=true
// isInline=false
// #members=2

// checkpoint byps.gen.j.GenSerStruct:274
@SuppressWarnings("all")
public class BSerializer_744806851 extends BSerializer {
	
	public final static BSerializer instance = new BSerializer_744806851();
	
	public BSerializer_744806851() {
		super(744806851);
	}
	
	public BSerializer_744806851(int typeId) {
		super(typeId);
	}
	
	
	@Override
	public void write(final Object obj1, final BOutput bout1, final long version) throws BException {
		final BRequest_FileSystemService_uploadFile obj = (BRequest_FileSystemService_uploadFile)obj1;		
		final BOutputBin bout = (BOutputBin)bout1;
		final BBufferBin bbuf = bout.bbuf;
		bbuf.putString(obj.path);
		bbuf.putString(obj.url);
	}
	
	@Override
	public Object read(final Object obj1, final BInput bin1, final long version) throws BException {
		final BInputBin bin = (BInputBin)bin1;
		final BRequest_FileSystemService_uploadFile obj = (BRequest_FileSystemService_uploadFile)(obj1 != null ? obj1 : bin.onObjectCreated(new BRequest_FileSystemService_uploadFile()));
		
		final BBufferBin bbuf = bin.bbuf;
		
		obj.path = bbuf.getString();
		obj.url = bbuf.getString();
		
		return obj;
	}
	
}
