package com.wilutions.jsfs;

/*
 * Serializer for com.wilutions.jsfs.BRequest_DispatcherService_keepAlive
 * 
 * THIS FILE HAS BEEN GENERATED BY class byps.gen.j.GenSerStruct DO NOT MODIFY.
 */

import byps.*;

// DEBUG
// isEnum=false
// isFinal=true
// isInline=false
// #members=1

// checkpoint byps.gen.j.GenSerStruct:274
@SuppressWarnings("all")
public class BSerializer_1609273478 extends BSerializer {
	
	public final static BSerializer instance = new BSerializer_1609273478();
	
	public BSerializer_1609273478() {
		super(1609273478);
	}
	
	public BSerializer_1609273478(int typeId) {
		super(typeId);
	}
	
	
	@Override
	public void write(final Object obj1, final BOutput bout1, final long version) throws BException {
		final BRequest_DispatcherService_keepAlive obj = (BRequest_DispatcherService_keepAlive)obj1;		
		final BOutputBin bout = (BOutputBin)bout1;
		final BBufferBin bbuf = bout.bbuf;
		bbuf.putString(obj.token);
	}
	
	@Override
	public Object read(final Object obj1, final BInput bin1, final long version) throws BException {
		final BInputBin bin = (BInputBin)bin1;
		final BRequest_DispatcherService_keepAlive obj = (BRequest_DispatcherService_keepAlive)(obj1 != null ? obj1 : bin.onObjectCreated(new BRequest_DispatcherService_keepAlive()));
		
		final BBufferBin bbuf = bin.bbuf;
		
		obj.token = bbuf.getString();
		
		return obj;
	}
	
}
