package com.wilutions.jsfs;

/*
 * Serializer for com.wilutions.jsfs.FileInfo
 * 
 * THIS FILE HAS BEEN GENERATED BY class byps.gen.j.GenSerStruct DO NOT MODIFY.
 */

import byps.*;

// DEBUG
// isEnum=false
// isFinal=false
// isInline=false
// #members=7

// checkpoint byps.gen.j.GenSerStruct:274
@SuppressWarnings("all")
public class BSerializer_1100528120 extends BSerializer {
	
	public final static BSerializer instance = new BSerializer_1100528120();
	
	public BSerializer_1100528120() {
		super(1100528120);
	}
	
	public BSerializer_1100528120(int typeId) {
		super(typeId);
	}
	
	
	@Override
	public void write(final Object obj1, final BOutput bout1, final long version) throws BException {
		final FileInfo obj = (FileInfo)obj1;		
		final BOutputBin bout = (BOutputBin)bout1;
		final BBufferBin bbuf = bout.bbuf;
		bbuf.putBoolean(obj.directory);
		bbuf.putDate(obj.lastModified);
		bbuf.putString(obj.name);
		bbuf.putBoolean(obj.readonly);
		bbuf.putInt(obj.size);
		bbuf.putLong(obj.sizeL);
		bout.writeObj(obj.icon, false, com.wilutions.jsfs.BSerializer_1374008726.instance);
	}
	
	@Override
	public Object read(final Object obj1, final BInput bin1, final long version) throws BException {
		final BInputBin bin = (BInputBin)bin1;
		final FileInfo obj = (FileInfo)(obj1 != null ? obj1 : bin.onObjectCreated(new FileInfo()));
		
		final BBufferBin bbuf = bin.bbuf;
		
		obj.directory = bbuf.getBoolean();
		obj.lastModified = bbuf.getDate();
		obj.name = bbuf.getString();
		obj.readonly = bbuf.getBoolean();
		obj.size = bbuf.getInt();
		obj.sizeL = bbuf.getLong();
		obj.icon = (byte[])bin.readObj(false, com.wilutions.jsfs.BSerializer_1374008726.instance);
		
		return obj;
	}
	
}
