package com.wilutions.jsfs;

/*
 * Serializer for com.wilutions.jsfs.ExecuteOptions
 * 
 * THIS FILE HAS BEEN GENERATED BY class byps.gen.j.GenSerStruct DO NOT MODIFY.
 */

import byps.*;

// DEBUG
// isEnum=false
// isFinal=false
// isInline=false
// #members=4

// checkpoint byps.gen.j.GenSerStruct:274
@SuppressWarnings("all")
public class BSerializer_1032737639 extends BSerializer {
	
	public final static BSerializer instance = new BSerializer_1032737639();
	
	public BSerializer_1032737639() {
		super(1032737639);
	}
	
	public BSerializer_1032737639(int typeId) {
		super(typeId);
	}
	
	
	@Override
	public void write(final Object obj1, final BOutput bout1, final long version) throws BException {
		final ExecuteOptions obj = (ExecuteOptions)obj1;		
		final BOutputBin bout = (BOutputBin)bout1;
		final BBufferBin bbuf = bout.bbuf;
		bbuf.putBoolean(obj.captureError);
		bbuf.putBoolean(obj.captureOutput);
		bbuf.putString(obj.extraInfo);
		bbuf.putString(obj.standardInput);
	}
	
	@Override
	public Object read(final Object obj1, final BInput bin1, final long version) throws BException {
		final BInputBin bin = (BInputBin)bin1;
		final ExecuteOptions obj = (ExecuteOptions)(obj1 != null ? obj1 : bin.onObjectCreated(new ExecuteOptions()));
		
		final BBufferBin bbuf = bin.bbuf;
		
		obj.captureError = bbuf.getBoolean();
		obj.captureOutput = bbuf.getBoolean();
		obj.extraInfo = bbuf.getString();
		obj.standardInput = bbuf.getString();
		
		return obj;
	}
	
}
