package com.wilutions.jsfs;

/*
 * Serializer for com.wilutions.jsfs.FileSystemServiceC
 * 
 * THIS FILE HAS BEEN GENERATED BY class byps.gen.j.GenSerStruct DO NOT MODIFY.
 */

import byps.*;

// DEBUG
// isEnum=false
// isFinal=false
// isInline=false
// #members=1

// checkpoint byps.gen.j.GenSerStruct:274
@SuppressWarnings("all")
public class BSerializer_1381128722 extends BSerializer {
	
	public final static BSerializer instance = new BSerializer_1381128722();
	
	public BSerializer_1381128722() {
		super(1381128722);
	}
	
	public BSerializer_1381128722(int typeId) {
		super(typeId);
	}
	
	
	@Override
	public void write(final Object obj1, final BOutput bout1, final long version) throws BException {
		final FileSystemServiceC obj = (FileSystemServiceC)obj1;		
		final BOutputBin bout = (BOutputBin)bout1;
		final BBufferBin bbuf = bout.bbuf;
	}
	
	@Override
	public Object read(final Object obj1, final BInput bin1, final long version) throws BException {
		final BInputBin bin = (BInputBin)bin1;
		final FileSystemServiceC obj = (FileSystemServiceC)(obj1 != null ? obj1 : bin.onObjectCreated(new FileSystemServiceC()));
		
		final BBufferBin bbuf = bin.bbuf;
		
		
		return obj;
	}
	
}
