package com.wilutions.jsfs;

/*
 * Serializer for com.wilutions.jsfs.BRequest_FileSystemService_beginWatchFolder
 * 
 * THIS FILE HAS BEEN GENERATED BY class byps.gen.j.GenSerStruct DO NOT MODIFY.
 */

import byps.*;

// DEBUG
// isEnum=false
// isFinal=true
// isInline=false
// #members=3

// checkpoint byps.gen.j.GenSerStruct:274
@SuppressWarnings("all")
public class BSerializer_1762179110 extends BSerializer {
	
	public final static BSerializer instance = new BSerializer_1762179110();
	
	public BSerializer_1762179110() {
		super(1762179110);
	}
	
	public BSerializer_1762179110(int typeId) {
		super(typeId);
	}
	
	
	@Override
	public void write(final Object obj1, final BOutput bout1, final long version) throws BException {
		final BRequest_FileSystemService_beginWatchFolder obj = (BRequest_FileSystemService_beginWatchFolder)obj1;		
		final BOutputBin bout = (BOutputBin)bout1;
		final BBufferBin bbuf = bout.bbuf;
		bbuf.putString(obj.dir);
		bbuf.putString(obj.extraInfo);
		bbuf.putBoolean(obj.recursive);
	}
	
	@Override
	public Object read(final Object obj1, final BInput bin1, final long version) throws BException {
		final BInputBin bin = (BInputBin)bin1;
		final BRequest_FileSystemService_beginWatchFolder obj = (BRequest_FileSystemService_beginWatchFolder)(obj1 != null ? obj1 : bin.onObjectCreated(new BRequest_FileSystemService_beginWatchFolder()));
		
		final BBufferBin bbuf = bin.bbuf;
		
		obj.dir = bbuf.getString();
		obj.extraInfo = bbuf.getString();
		obj.recursive = bbuf.getBoolean();
		
		return obj;
	}
	
}
