package com.wilutions.jsfs;

/*
 * 
 * THIS FILE HAS BEEN GENERATED BY class byps.gen.j.GenRemoteSkeleton DO NOT MODIFY.
 */

import byps.*;

/**
 * This class provides a skeleton implementation of the interface FileSystemNotify.
 * Your interface implementation class has to be derived from this skeleton.
 * Either provide an asynchronous or a synchronous function in your subclass.
 * The framework calls only the asynchronous function.
 */
@SuppressWarnings("all")
public class BSkeleton_FileSystemNotify extends BSkeleton implements FileSystemNotifyAsync {
	
	public final static long serialVersionUID = 544795964L;
	
	// checkpoint byps.gen.j.PrintContext:365
	public void notify(NotifyInfo notifyInfo) throws RemoteException {
		throw new BException(BExceptionC.UNSUPPORTED_METHOD, "");
	}
	// checkpoint byps.gen.j.PrintContext:409
	public void notify(NotifyInfo notifyInfo, final BAsyncResult<Object> asyncResult) {
		try {
			notify(notifyInfo);
			asyncResult.setAsyncResult(null, null);
		} catch (Throwable e) {
			asyncResult.setAsyncResult(null, e);
		}
	}
	
	
}
