package com.wilutions.jsfs;

/*
 * 
 * THIS FILE HAS BEEN GENERATED BY class byps.gen.j.GenRemoteStub DO NOT MODIFY.
 */

import byps.*;

// checkpoint byps.gen.j.GenRemoteStub:164
public class BStub_DispatcherService extends BStub implements DispatcherServiceAsync, java.io.Serializable {
	
	// checkpoint byps.gen.j.GenRemoteStub:145
	public final static long serialVersionUID = 1153231042L;
	
	public BStub_DispatcherService(final BTransport transport) {
		super(transport);		
	}
	
	// checkpoint byps.gen.j.PrintContext:365
	public void registerService(java.lang.String token, FileSystemService service) throws RemoteException {
		// checkpoint byps.gen.j.GenRemoteStub:46
		final BSyncResult<Object> asyncResult = new BSyncResult<Object>();		
		registerService(token, service, asyncResult);
		asyncResult.getResult();		
	}
	// checkpoint byps.gen.j.PrintContext:409
	public void registerService(java.lang.String token, FileSystemService service, final BAsyncResult<Object> asyncResult) {
		// checkpoint byps.gen.j.GenRemoteStub:113
		BRequest_DispatcherService_registerService req = new BRequest_DispatcherService_registerService();		
		req.token = token;
		req.service = service;
		transport.sendMethod(req, asyncResult);
	}
	
	// checkpoint byps.gen.j.PrintContext:365
	public void unregisterService(java.lang.String token) throws RemoteException {
		// checkpoint byps.gen.j.GenRemoteStub:46
		final BSyncResult<Object> asyncResult = new BSyncResult<Object>();		
		unregisterService(token, asyncResult);
		asyncResult.getResult();		
	}
	// checkpoint byps.gen.j.PrintContext:409
	public void unregisterService(java.lang.String token, final BAsyncResult<Object> asyncResult) {
		// checkpoint byps.gen.j.GenRemoteStub:113
		BRequest_DispatcherService_unregisterService req = new BRequest_DispatcherService_unregisterService();		
		req.token = token;
		transport.sendMethod(req, asyncResult);
	}
	
	// checkpoint byps.gen.j.PrintContext:365
	public FileSystemService getService(java.lang.String token, boolean onlyHere) throws RemoteException {
		// checkpoint byps.gen.j.GenRemoteStub:46
		final BSyncResult<FileSystemService> asyncResult = new BSyncResult<FileSystemService>();		
		getService(token, onlyHere, asyncResult);
		return asyncResult.getResult();		
	}
	// checkpoint byps.gen.j.PrintContext:409
	public void getService(java.lang.String token, boolean onlyHere, final BAsyncResult<FileSystemService> asyncResult) {
		// checkpoint byps.gen.j.GenRemoteStub:113
		BRequest_DispatcherService_getService req = new BRequest_DispatcherService_getService();		
		req.token = token;
		req.onlyHere = onlyHere;
		transport.sendMethod(req, asyncResult);
	}
	
	// checkpoint byps.gen.j.PrintContext:365
	public void registerNotifyService(java.lang.String token, FileSystemNotify service) throws RemoteException {
		// checkpoint byps.gen.j.GenRemoteStub:46
		final BSyncResult<Object> asyncResult = new BSyncResult<Object>();		
		registerNotifyService(token, service, asyncResult);
		asyncResult.getResult();		
	}
	// checkpoint byps.gen.j.PrintContext:409
	public void registerNotifyService(java.lang.String token, FileSystemNotify service, final BAsyncResult<Object> asyncResult) {
		// checkpoint byps.gen.j.GenRemoteStub:113
		BRequest_DispatcherService_registerNotifyService req = new BRequest_DispatcherService_registerNotifyService();		
		req.token = token;
		req.service = service;
		transport.sendMethod(req, asyncResult);
	}
	
	// checkpoint byps.gen.j.PrintContext:365
	public void unregisterNotifyService(java.lang.String token) throws RemoteException {
		// checkpoint byps.gen.j.GenRemoteStub:46
		final BSyncResult<Object> asyncResult = new BSyncResult<Object>();		
		unregisterNotifyService(token, asyncResult);
		asyncResult.getResult();		
	}
	// checkpoint byps.gen.j.PrintContext:409
	public void unregisterNotifyService(java.lang.String token, final BAsyncResult<Object> asyncResult) {
		// checkpoint byps.gen.j.GenRemoteStub:113
		BRequest_DispatcherService_unregisterNotifyService req = new BRequest_DispatcherService_unregisterNotifyService();		
		req.token = token;
		transport.sendMethod(req, asyncResult);
	}
	
	// checkpoint byps.gen.j.PrintContext:365
	public FileSystemNotify getNotifyService(java.lang.String token, boolean onlyHere) throws RemoteException {
		// checkpoint byps.gen.j.GenRemoteStub:46
		final BSyncResult<FileSystemNotify> asyncResult = new BSyncResult<FileSystemNotify>();		
		getNotifyService(token, onlyHere, asyncResult);
		return asyncResult.getResult();		
	}
	// checkpoint byps.gen.j.PrintContext:409
	public void getNotifyService(java.lang.String token, boolean onlyHere, final BAsyncResult<FileSystemNotify> asyncResult) {
		// checkpoint byps.gen.j.GenRemoteStub:113
		BRequest_DispatcherService_getNotifyService req = new BRequest_DispatcherService_getNotifyService();		
		req.token = token;
		req.onlyHere = onlyHere;
		transport.sendMethod(req, asyncResult);
	}
	
	// checkpoint byps.gen.j.PrintContext:365
	public void keepAlive(java.lang.String token) throws RemoteException {
		// checkpoint byps.gen.j.GenRemoteStub:46
		final BSyncResult<Object> asyncResult = new BSyncResult<Object>();		
		keepAlive(token, asyncResult);
		asyncResult.getResult();		
	}
	// checkpoint byps.gen.j.PrintContext:409
	public void keepAlive(java.lang.String token, final BAsyncResult<Object> asyncResult) {
		// checkpoint byps.gen.j.GenRemoteStub:113
		BRequest_DispatcherService_keepAlive req = new BRequest_DispatcherService_keepAlive();		
		req.token = token;
		transport.sendMethod(req, asyncResult);
	}
	
	
}
