package com.wilutions.jsfs;

/*
 * 
 * THIS FILE HAS BEEN GENERATED BY class byps.gen.j.GenRemoteClassAsync DO NOT MODIFY.
 */

import byps.*;

// checkpoint byps.gen.j.GenRemoteClassAsync:68
public interface FileSystemNotifyAsync extends BRemote, 
	FileSystemNotify {
	/**
	 * Notify the browser about an event.
	 * @param notifyInfo NotifyInfo or ExecuteNotifyInfo object.
	 * @throws RemoteException
	*/
	// checkpoint byps.gen.j.PrintContext:365
	public void notify(NotifyInfo notifyInfo) throws RemoteException;
	// checkpoint byps.gen.j.PrintContext:409
	public void notify(NotifyInfo notifyInfo, final BAsyncResult<Object> asyncResult) ;
	
	
}
