package com.wilutions.jsfs;

/*
 * 
 * THIS FILE HAS BEEN GENERATED BY class byps.gen.j.GenRegistry DO NOT MODIFY.
 */

import byps.*;

public class JRegistry_JSFS extends BRegistry { 

	public JRegistry_JSFS() {
		super(BBinaryModel.JSON);
	}
	
	private static BRegisteredSerializer[] serializers = new BRegisteredSerializer[] {
		new BRegisteredSerializer(9906860, "com.wilutions.jsfs.JSerializer_9906860"),
		new BRegisteredSerializer(145996442, "com.wilutions.jsfs.JSerializer_145996442"),
		new BRegisteredSerializer(169662220, "com.wilutions.jsfs.JSerializer_169662220"),
		new BRegisteredSerializer(240503306, "com.wilutions.jsfs.JSerializer_240503306"),
		new BRegisteredSerializer(481066845, "com.wilutions.jsfs.JSerializer_481066845"),
		new BRegisteredSerializer(544795964, "com.wilutions.jsfs.JSerializer_544795964"),
		new BRegisteredSerializer(566696346, "com.wilutions.jsfs.JSerializer_566696346"),
		new BRegisteredSerializer(575037953, "com.wilutions.jsfs.JSerializer_575037953"),
		new BRegisteredSerializer(665368294, "com.wilutions.jsfs.JSerializer_665368294"),
		new BRegisteredSerializer(706034600, "com.wilutions.jsfs.JSerializer_706034600"),
		new BRegisteredSerializer(744806851, "com.wilutions.jsfs.JSerializer_744806851"),
		new BRegisteredSerializer(964561591, "com.wilutions.jsfs.JSerializer_964561591"),
		new BRegisteredSerializer(964561595, "com.wilutions.jsfs.JSerializer_964561595"),
		new BRegisteredSerializer(964561600, "com.wilutions.jsfs.JSerializer_964561600"),
		new BRegisteredSerializer(979378962, "com.wilutions.jsfs.JSerializer_979378962"),
		new BRegisteredSerializer(1032737639, "com.wilutions.jsfs.JSerializer_1032737639"),
		new BRegisteredSerializer(1078989294, "com.wilutions.jsfs.JSerializer_1078989294"),
		new BRegisteredSerializer(1090607752, "com.wilutions.jsfs.JSerializer_1090607752"),
		new BRegisteredSerializer(1092766252, "com.wilutions.jsfs.JSerializer_1092766252"),
		new BRegisteredSerializer(1100528120, "com.wilutions.jsfs.JSerializer_1100528120"),
		new BRegisteredSerializer(1124739608, "com.wilutions.jsfs.JSerializer_1124739608"),
		new BRegisteredSerializer(1131301080, "com.wilutions.jsfs.JSerializer_1131301080"),
		new BRegisteredSerializer(1153231042, "com.wilutions.jsfs.JSerializer_1153231042"),
		new BRegisteredSerializer(1274131736, "com.wilutions.jsfs.JSerializer_1274131736"),
		new BRegisteredSerializer(1354059712, "com.wilutions.jsfs.JSerializer_1354059712"),
		new BRegisteredSerializer(1366717454, "com.wilutions.jsfs.JSerializer_1366717454"),
		new BRegisteredSerializer(1381128722, "com.wilutions.jsfs.JSerializer_1381128722"),
		new BRegisteredSerializer(1439246415, "com.wilutions.jsfs.JSerializer_1439246415"),
		new BRegisteredSerializer(1542825705, "com.wilutions.jsfs.JSerializer_1542825705"),
		new BRegisteredSerializer(1609273478, "com.wilutions.jsfs.JSerializer_1609273478"),
		new BRegisteredSerializer(1733426638, "com.wilutions.jsfs.JSerializer_1733426638"),
		new BRegisteredSerializer(1762179110, "com.wilutions.jsfs.JSerializer_1762179110"),
		new BRegisteredSerializer(1815527676, "com.wilutions.jsfs.JSerializer_1815527676"),
		new BRegisteredSerializer(1824869366, "com.wilutions.jsfs.JSerializer_1824869366"),
		new BRegisteredSerializer(1833696176, "com.wilutions.jsfs.JSerializer_1833696176"),
		new BRegisteredSerializer(1849102471, "com.wilutions.jsfs.JSerializer_1849102471"),
		new BRegisteredSerializer(1888107655, "com.wilutions.jsfs.JSerializer_1888107655"),
		new BRegisteredSerializer(1925305675, "com.wilutions.jsfs.JSerializer_1925305675"),
	};
	@Override
	protected BRegisteredSerializer[] getSortedSerializers() {
		return serializers;
	}
}
