package com.wilutions.jsfs;

/*
 * Serializer for com.wilutions.jsfs.FileInfo
 * 
 * THIS FILE HAS BEEN GENERATED BY class byps.gen.j.GenSerStructJson DO NOT MODIFY.
 */

import byps.*;

// DEBUG
// isEnum=false
// isFinal=false
// isInline=false
// #members=6

// checkpoint byps.gen.j.GenSerStruct:274
@SuppressWarnings("all")
public class JSerializer_1100528120 extends JSerializer_Object {
	
	public final static BSerializer instance = new JSerializer_1100528120();
	
	public JSerializer_1100528120() {
		super(1100528120);
	}
	
	public JSerializer_1100528120(int typeId) {
		super(typeId);
	}
	
	
	@Override
	public void internalWrite(final Object obj1, final BOutputJson bout, final BBufferJson bbuf) throws BException {
		final FileInfo obj = (FileInfo)obj1;		
		bbuf.putBoolean("directory", obj.directory);
		bbuf.putDate("lastModified", obj.lastModified);
		bbuf.putString("name", obj.name);
		bbuf.putBoolean("readonly", obj.readonly);
		bbuf.putInt("size", obj.size);
		bbuf.putLong("sizeL", obj.sizeL);
	}
	
	@Override
	public Object internalRead(final Object obj1, final BInputJson bin) throws BException {
		final FileInfo obj = (FileInfo)(obj1 != null ? obj1 : bin.onObjectCreated(new FileInfo()));
		
		final BJsonObject js = bin.currentObject;
		obj.directory = js.getBoolean("directory");
		obj.lastModified = js.getDate("lastModified");
		obj.name = js.getString("name");
		obj.readonly = js.getBoolean("readonly");
		obj.size = js.getInt("size");
		obj.sizeL = js.getLong("sizeL");
		
		return obj;
	}
	
}
