package com.wilutions.jsfs;

/*
 * Serializer for java.util.List<com.wilutions.jsfs.FileInfo>
 * 
 * THIS FILE HAS BEEN GENERATED BY class byps.gen.j.GenSerListJson DO NOT MODIFY.
 */

import byps.*;
import java.util.*;

@SuppressWarnings("all")
public class JSerializer_1439246415 extends BSerializer {
	
	public final static BSerializer instance = new JSerializer_1439246415();
	
	public JSerializer_1439246415() {
		super(1439246415);
	}
	
	@Override
	public Object read(final Object obj1, final BInput bin1, final long version) throws BException {
		final BInputJson bin = (BInputJson)bin1;
		final BBufferJson bbuf = bin.bbuf;
		final int n = bin.currentObject.size();
		final ArrayList<com.wilutions.jsfs.FileInfo> arr = new ArrayList<com.wilutions.jsfs.FileInfo>(n);
		bin.onObjectCreated(arr);
		for (int i0 = 0; i0 < n; i0++) {
			com.wilutions.jsfs.FileInfo obj = (com.wilutions.jsfs.FileInfo)bin.readObj(i0, false, null);
			arr.add(obj);
		}
		return arr;
	}
	
	@Override
	public void write(Object obj1, BOutput bout1, final long version)  throws BException {
		BOutputJson bout = (BOutputJson)bout1;
		BBufferJson bbuf = bout.bbuf;
		java.util.List<com.wilutions.jsfs.FileInfo> arr = (java.util.List<com.wilutions.jsfs.FileInfo>)obj1;
		int n = arr.size();
		bbuf.beginArray();
		for (com.wilutions.jsfs.FileInfo obj : arr) {
			// checkpoint byps.gen.j.PrintContext:313
			bout.writeObj(null, obj, false, null);
		}
		bbuf.endArray();
	}
	
}
