package com.wilutions.jsfs;

/*
 * Serializer for com.wilutions.jsfs.BResult_15
 * 
 * THIS FILE HAS BEEN GENERATED BY class byps.gen.j.GenSerStructJson DO NOT MODIFY.
 */

import byps.*;

// DEBUG
// isEnum=false
// isFinal=true
// isInline=false
// #members=1

// checkpoint byps.gen.j.GenSerStruct:274
@SuppressWarnings("all")
public class JSerializer_964561595 extends JSerializer_Object {
	
	public final static BSerializer instance = new JSerializer_964561595();
	
	public JSerializer_964561595() {
		super(964561595);
	}
	
	public JSerializer_964561595(int typeId) {
		super(typeId);
	}
	
	
	@Override
	public void internalWrite(final Object obj1, final BOutputJson bout, final BBufferJson bbuf) throws BException {
		final BResult_15 obj = (BResult_15)obj1;		
		bout.writeObj("result",obj.result, false, null);
	}
	
	@Override
	public Object internalRead(final Object obj1, final BInputJson bin) throws BException {
		final BResult_15 obj = (BResult_15)(obj1 != null ? obj1 : bin.onObjectCreated(new BResult_15()));
		
		final BJsonObject js = bin.currentObject;
		obj.result = (java.io.InputStream)bin.readObj("result", false, null);
		
		return obj;
	}
	
}
