package com.wilutions.jsfs;

/*
 * Serializer for com.wilutions.jsfs.BStub_DispatcherService
 * 
 * THIS FILE HAS BEEN GENERATED BY class byps.gen.j.GenSerStub DO NOT MODIFY.
 */

import byps.*;
@SuppressWarnings("all")
public class JSerializer_1153231042 extends JSerializer_16 {
	
	public final static BSerializer instance = new JSerializer_1153231042();
	
	public JSerializer_1153231042() {
		super(1153231042);
	}
	
	@Override
	public BRemote internalCreate(final BTransport transport) throws BException {
		return new BStub_DispatcherService(transport);
	}
	
}
