package com.wilutions.jsfs;

/*
 * Serializer for com.wilutions.jsfs.BRequest_FileSystemService_findFiles
 * 
 * THIS FILE HAS BEEN GENERATED BY class byps.gen.j.GenSerStructJson DO NOT MODIFY.
 */

import byps.*;

// DEBUG
// isEnum=false
// isFinal=true
// isInline=false
// #members=2

// checkpoint byps.gen.j.GenSerStruct:274
@SuppressWarnings("all")
public class JSerializer_1131301080 extends JSerializer_Object {
	
	public final static BSerializer instance = new JSerializer_1131301080();
	
	public JSerializer_1131301080() {
		super(1131301080);
	}
	
	public JSerializer_1131301080(int typeId) {
		super(typeId);
	}
	
	
	@Override
	public void internalWrite(final Object obj1, final BOutputJson bout, final BBufferJson bbuf) throws BException {
		final BRequest_FileSystemService_findFiles obj = (BRequest_FileSystemService_findFiles)obj1;		
		bbuf.putString("path", obj.path);
		bout.writeObj("findOptions",obj.findOptions, false, null);
	}
	
	@Override
	public Object internalRead(final Object obj1, final BInputJson bin) throws BException {
		final BRequest_FileSystemService_findFiles obj = (BRequest_FileSystemService_findFiles)(obj1 != null ? obj1 : bin.onObjectCreated(new BRequest_FileSystemService_findFiles()));
		
		final BJsonObject js = bin.currentObject;
		obj.path = js.getString("path");
		obj.findOptions = (com.wilutions.jsfs.FindOptions)bin.readObj("findOptions", false, null);
		
		return obj;
	}
	
}
