package com.wilutions.jsfs;

/*
 * Serializer for com.wilutions.jsfs.BRequest_FileSystemService_readAllText
 * 
 * THIS FILE HAS BEEN GENERATED BY class byps.gen.j.GenSerStructJson DO NOT MODIFY.
 */

import byps.*;

// DEBUG
// isEnum=false
// isFinal=true
// isInline=false
// #members=1

// checkpoint byps.gen.j.GenSerStruct:274
@SuppressWarnings("all")
public class JSerializer_1078989294 extends JSerializer_Object {
	
	public final static BSerializer instance = new JSerializer_1078989294();
	
	public JSerializer_1078989294() {
		super(1078989294);
	}
	
	public JSerializer_1078989294(int typeId) {
		super(typeId);
	}
	
	
	@Override
	public void internalWrite(final Object obj1, final BOutputJson bout, final BBufferJson bbuf) throws BException {
		final BRequest_FileSystemService_readAllText obj = (BRequest_FileSystemService_readAllText)obj1;		
		bbuf.putString("path", obj.path);
	}
	
	@Override
	public Object internalRead(final Object obj1, final BInputJson bin) throws BException {
		final BRequest_FileSystemService_readAllText obj = (BRequest_FileSystemService_readAllText)(obj1 != null ? obj1 : bin.onObjectCreated(new BRequest_FileSystemService_readAllText()));
		
		final BJsonObject js = bin.currentObject;
		obj.path = js.getString("path");
		
		return obj;
	}
	
}
