package com.wilutions.jsfs;

/*
 * Serializer for com.wilutions.jsfs.BResult_336045129
 * 
 * THIS FILE HAS BEEN GENERATED BY class byps.gen.j.GenSerStructJson DO NOT MODIFY.
 */

import byps.*;

// DEBUG
// isEnum=false
// isFinal=true
// isInline=false
// #members=1

// checkpoint byps.gen.j.GenSerStruct:274
@SuppressWarnings("all")
public class JSerializer_1815527676 extends JSerializer_Object {
	
	public final static BSerializer instance = new JSerializer_1815527676();
	
	public JSerializer_1815527676() {
		super(1815527676);
	}
	
	public JSerializer_1815527676(int typeId) {
		super(typeId);
	}
	
	
	@Override
	public void internalWrite(final Object obj1, final BOutputJson bout, final BBufferJson bbuf) throws BException {
		final BResult_336045129 obj = (BResult_336045129)obj1;		
		bout.writeObj("result",obj.result, false, null);
	}
	
	@Override
	public Object internalRead(final Object obj1, final BInputJson bin) throws BException {
		final BResult_336045129 obj = (BResult_336045129)(obj1 != null ? obj1 : bin.onObjectCreated(new BResult_336045129()));
		
		final BJsonObject js = bin.currentObject;
		obj.result = (com.wilutions.jsfs.FileSystemService)bin.readObj("result", false, null);
		
		return obj;
	}
	
}
