package com.wilutions.jsfs;

/*
 * Serializer for com.wilutions.jsfs.BRequest_DispatcherService_keepAlive
 * 
 * THIS FILE HAS BEEN GENERATED BY class byps.gen.j.GenSerStructJson DO NOT MODIFY.
 */

import byps.*;

// DEBUG
// isEnum=false
// isFinal=true
// isInline=false
// #members=1

// checkpoint byps.gen.j.GenSerStruct:274
@SuppressWarnings("all")
public class JSerializer_1609273478 extends JSerializer_Object {
	
	public final static BSerializer instance = new JSerializer_1609273478();
	
	public JSerializer_1609273478() {
		super(1609273478);
	}
	
	public JSerializer_1609273478(int typeId) {
		super(typeId);
	}
	
	
	@Override
	public void internalWrite(final Object obj1, final BOutputJson bout, final BBufferJson bbuf) throws BException {
		final BRequest_DispatcherService_keepAlive obj = (BRequest_DispatcherService_keepAlive)obj1;		
		bbuf.putString("token", obj.token);
	}
	
	@Override
	public Object internalRead(final Object obj1, final BInputJson bin) throws BException {
		final BRequest_DispatcherService_keepAlive obj = (BRequest_DispatcherService_keepAlive)(obj1 != null ? obj1 : bin.onObjectCreated(new BRequest_DispatcherService_keepAlive()));
		
		final BJsonObject js = bin.currentObject;
		obj.token = js.getString("token");
		
		return obj;
	}
	
}
