package com.wilutions.jsfs;

/*
 * Serializer for com.wilutions.jsfs.ExecuteOptions
 * 
 * THIS FILE HAS BEEN GENERATED BY class byps.gen.j.GenSerStructJson DO NOT MODIFY.
 */

import byps.*;

// DEBUG
// isEnum=false
// isFinal=false
// isInline=false
// #members=4

// checkpoint byps.gen.j.GenSerStruct:274
@SuppressWarnings("all")
public class JSerializer_1032737639 extends JSerializer_Object {
	
	public final static BSerializer instance = new JSerializer_1032737639();
	
	public JSerializer_1032737639() {
		super(1032737639);
	}
	
	public JSerializer_1032737639(int typeId) {
		super(typeId);
	}
	
	
	@Override
	public void internalWrite(final Object obj1, final BOutputJson bout, final BBufferJson bbuf) throws BException {
		final ExecuteOptions obj = (ExecuteOptions)obj1;		
		bbuf.putBoolean("captureError", obj.captureError);
		bbuf.putBoolean("captureOutput", obj.captureOutput);
		bbuf.putString("extraInfo", obj.extraInfo);
		bbuf.putString("standardInput", obj.standardInput);
	}
	
	@Override
	public Object internalRead(final Object obj1, final BInputJson bin) throws BException {
		final ExecuteOptions obj = (ExecuteOptions)(obj1 != null ? obj1 : bin.onObjectCreated(new ExecuteOptions()));
		
		final BJsonObject js = bin.currentObject;
		obj.captureError = js.getBoolean("captureError");
		obj.captureOutput = js.getBoolean("captureOutput");
		obj.extraInfo = js.getString("extraInfo");
		obj.standardInput = js.getString("standardInput");
		
		return obj;
	}
	
}
