package com.wilutions.jsfs;

/*
 * Serializer for com.wilutions.jsfs.BRequest_FileSystemNotify_notify
 * 
 * THIS FILE HAS BEEN GENERATED BY class byps.gen.j.GenSerStructJson DO NOT MODIFY.
 */

import byps.*;

// DEBUG
// isEnum=false
// isFinal=true
// isInline=false
// #members=1

// checkpoint byps.gen.j.GenSerStruct:274
@SuppressWarnings("all")
public class JSerializer_481066845 extends JSerializer_Object {
	
	public final static BSerializer instance = new JSerializer_481066845();
	
	public JSerializer_481066845() {
		super(481066845);
	}
	
	public JSerializer_481066845(int typeId) {
		super(typeId);
	}
	
	
	@Override
	public void internalWrite(final Object obj1, final BOutputJson bout, final BBufferJson bbuf) throws BException {
		final BRequest_FileSystemNotify_notify obj = (BRequest_FileSystemNotify_notify)obj1;		
		bout.writeObj("notifyInfo",obj.notifyInfo, false, null);
	}
	
	@Override
	public Object internalRead(final Object obj1, final BInputJson bin) throws BException {
		final BRequest_FileSystemNotify_notify obj = (BRequest_FileSystemNotify_notify)(obj1 != null ? obj1 : bin.onObjectCreated(new BRequest_FileSystemNotify_notify()));
		
		final BJsonObject js = bin.currentObject;
		obj.notifyInfo = (com.wilutions.jsfs.NotifyInfo)bin.readObj("notifyInfo", false, null);
		
		return obj;
	}
	
}
