package com.wilutions.jsfs;

/*
 * Serializer for com.wilutions.jsfs.BRequest_FileSystemService_beginWatchFolder
 * 
 * THIS FILE HAS BEEN GENERATED BY class byps.gen.j.GenSerStructJson DO NOT MODIFY.
 */

import byps.*;

// DEBUG
// isEnum=false
// isFinal=true
// isInline=false
// #members=3

// checkpoint byps.gen.j.GenSerStruct:274
@SuppressWarnings("all")
public class JSerializer_1762179110 extends JSerializer_Object {
	
	public final static BSerializer instance = new JSerializer_1762179110();
	
	public JSerializer_1762179110() {
		super(1762179110);
	}
	
	public JSerializer_1762179110(int typeId) {
		super(typeId);
	}
	
	
	@Override
	public void internalWrite(final Object obj1, final BOutputJson bout, final BBufferJson bbuf) throws BException {
		final BRequest_FileSystemService_beginWatchFolder obj = (BRequest_FileSystemService_beginWatchFolder)obj1;		
		bbuf.putString("dir", obj.dir);
		bbuf.putString("extraInfo", obj.extraInfo);
		bbuf.putBoolean("recursive", obj.recursive);
	}
	
	@Override
	public Object internalRead(final Object obj1, final BInputJson bin) throws BException {
		final BRequest_FileSystemService_beginWatchFolder obj = (BRequest_FileSystemService_beginWatchFolder)(obj1 != null ? obj1 : bin.onObjectCreated(new BRequest_FileSystemService_beginWatchFolder()));
		
		final BJsonObject js = bin.currentObject;
		obj.dir = js.getString("dir");
		obj.extraInfo = js.getString("extraInfo");
		obj.recursive = js.getBoolean("recursive");
		
		return obj;
	}
	
}
