package com.wilutions.jsfs;

/*
 * Serializer for com.wilutions.jsfs.FindOptions
 * 
 * THIS FILE HAS BEEN GENERATED BY class byps.gen.j.GenSerStructJson DO NOT MODIFY.
 */

import byps.*;

// DEBUG
// isEnum=false
// isFinal=false
// isInline=false
// #members=1

// checkpoint byps.gen.j.GenSerStruct:274
@SuppressWarnings("all")
public class JSerializer_1092766252 extends JSerializer_Object {
	
	public final static BSerializer instance = new JSerializer_1092766252();
	
	public JSerializer_1092766252() {
		super(1092766252);
	}
	
	public JSerializer_1092766252(int typeId) {
		super(typeId);
	}
	
	
	@Override
	public void internalWrite(final Object obj1, final BOutputJson bout, final BBufferJson bbuf) throws BException {
		final FindOptions obj = (FindOptions)obj1;		
		bbuf.putString("reserved", obj.reserved);
	}
	
	@Override
	public Object internalRead(final Object obj1, final BInputJson bin) throws BException {
		final FindOptions obj = (FindOptions)(obj1 != null ? obj1 : bin.onObjectCreated(new FindOptions()));
		
		final BJsonObject js = bin.currentObject;
		obj.reserved = js.getString("reserved");
		
		return obj;
	}
	
}
