package com.wilutions.jsfs;

/*
 * Serializer for com.wilutions.jsfs.BStub_FileSystemNotify
 * 
 * THIS FILE HAS BEEN GENERATED BY class byps.gen.j.GenSerStub DO NOT MODIFY.
 */

import byps.*;
@SuppressWarnings("all")
public class JSerializer_1816639285 extends JSerializer_16 {
	
	public final static BSerializer instance = new JSerializer_1816639285();
	
	public JSerializer_1816639285() {
		super(1816639285);
	}
	
	@Override
	public BRemote internalCreate(final BTransport transport) throws BException {
		return new BStub_FileSystemNotify(transport);
	}
	
}
