package com.wilutions.jsfs;

/*
 * Serializer for com.wilutions.jsfs.FormItem[]
 * 
 * THIS FILE HAS BEEN GENERATED BY class byps.gen.j.GenSerArrayJson DO NOT MODIFY.
 */

import byps.*;
@SuppressWarnings("all")
public class JSerializer_566696346 extends JSerializer_Array {
	
	public final static BSerializer instance = new JSerializer_566696346();
	
	public JSerializer_566696346() {
		super(566696346);
	}
	
	@Override
	public Object internalRead(final BInputJson bin) throws BException {
		final BJsonObject js0 = bin.currentObject;
		
		int n0 = 0;
		n0 = js0 != null ? js0.size() : 0;
		
		final FormItem[] arr =  new com.wilutions.jsfs.FormItem[n0];
		bin.onObjectCreated(arr);
		
		// read
		final FormItem[] a0 = arr;
		for (int i0 = 0; i0 < n0; i0++) {
			a0[i0] = (com.wilutions.jsfs.FormItem)bin.readObj(i0, false, null);
		}
		return arr;
		
	}
	
	@Override
	public void internalWrite(Object obj1, final BOutputJson bout, BBufferJson bbuf) throws BException {
		final FormItem[] arr = (FormItem[])obj1;
		
		// lengths
		final int n0 = arr.length;
		
		// write
		final FormItem[] a0 = arr;
		bbuf.beginArray();
		for (int i0 = 0; i0 < n0; i0++) {
			// checkpoint byps.gen.j.PrintContext:313
			bout.writeObj(null, a0[i0], false, null);
		}
		bbuf.endArray();
	}
	
}
