package com.wilutions.jsfs;

/*
 * Serializer for com.wilutions.jsfs.BRequest_FileSystemService_writeAllText
 * 
 * THIS FILE HAS BEEN GENERATED BY class byps.gen.j.GenSerStructJson DO NOT MODIFY.
 */

import byps.*;

// DEBUG
// isEnum=false
// isFinal=true
// isInline=false
// #members=2

// checkpoint byps.gen.j.GenSerStruct:274
@SuppressWarnings("all")
public class JSerializer_1925305675 extends JSerializer_Object {
	
	public final static BSerializer instance = new JSerializer_1925305675();
	
	public JSerializer_1925305675() {
		super(1925305675);
	}
	
	public JSerializer_1925305675(int typeId) {
		super(typeId);
	}
	
	
	@Override
	public void internalWrite(final Object obj1, final BOutputJson bout, final BBufferJson bbuf) throws BException {
		final BRequest_FileSystemService_writeAllText obj = (BRequest_FileSystemService_writeAllText)obj1;		
		bbuf.putString("path", obj.path);
		bbuf.putString("text", obj.text);
	}
	
	@Override
	public Object internalRead(final Object obj1, final BInputJson bin) throws BException {
		final BRequest_FileSystemService_writeAllText obj = (BRequest_FileSystemService_writeAllText)(obj1 != null ? obj1 : bin.onObjectCreated(new BRequest_FileSystemService_writeAllText()));
		
		final BJsonObject js = bin.currentObject;
		obj.path = js.getString("path");
		obj.text = js.getString("text");
		
		return obj;
	}
	
}
