package com.wilutions.jsfs;

/*
 * Serializer for com.wilutions.jsfs.BRequest_DispatcherService_getService
 * 
 * THIS FILE HAS BEEN GENERATED BY class byps.gen.j.GenSerStructJson DO NOT MODIFY.
 */

import byps.*;

// DEBUG
// isEnum=false
// isFinal=true
// isInline=false
// #members=2

// checkpoint byps.gen.j.GenSerStruct:274
@SuppressWarnings("all")
public class JSerializer_575037953 extends JSerializer_Object {
	
	public final static BSerializer instance = new JSerializer_575037953();
	
	public JSerializer_575037953() {
		super(575037953);
	}
	
	public JSerializer_575037953(int typeId) {
		super(typeId);
	}
	
	
	@Override
	public void internalWrite(final Object obj1, final BOutputJson bout, final BBufferJson bbuf) throws BException {
		final BRequest_DispatcherService_getService obj = (BRequest_DispatcherService_getService)obj1;		
		bbuf.putBoolean("onlyHere", obj.onlyHere);
		bbuf.putString("token", obj.token);
	}
	
	@Override
	public Object internalRead(final Object obj1, final BInputJson bin) throws BException {
		final BRequest_DispatcherService_getService obj = (BRequest_DispatcherService_getService)(obj1 != null ? obj1 : bin.onObjectCreated(new BRequest_DispatcherService_getService()));
		
		final BJsonObject js = bin.currentObject;
		obj.onlyHere = js.getBoolean("onlyHere");
		obj.token = js.getString("token");
		
		return obj;
	}
	
}
