package com.wilutions.jsfs;

/*
 * Serializer for com.wilutions.jsfs.BRequest_FileSystemService_endWatchFolder
 * 
 * THIS FILE HAS BEEN GENERATED BY class byps.gen.j.GenSerStructJson DO NOT MODIFY.
 */

import byps.*;

// DEBUG
// isEnum=false
// isFinal=true
// isInline=false
// #members=1

// checkpoint byps.gen.j.GenSerStruct:274
@SuppressWarnings("all")
public class JSerializer_1124739608 extends JSerializer_Object {
	
	public final static BSerializer instance = new JSerializer_1124739608();
	
	public JSerializer_1124739608() {
		super(1124739608);
	}
	
	public JSerializer_1124739608(int typeId) {
		super(typeId);
	}
	
	
	@Override
	public void internalWrite(final Object obj1, final BOutputJson bout, final BBufferJson bbuf) throws BException {
		final BRequest_FileSystemService_endWatchFolder obj = (BRequest_FileSystemService_endWatchFolder)obj1;		
		bbuf.putInt("handle", obj.handle);
	}
	
	@Override
	public Object internalRead(final Object obj1, final BInputJson bin) throws BException {
		final BRequest_FileSystemService_endWatchFolder obj = (BRequest_FileSystemService_endWatchFolder)(obj1 != null ? obj1 : bin.onObjectCreated(new BRequest_FileSystemService_endWatchFolder()));
		
		final BJsonObject js = bin.currentObject;
		obj.handle = js.getInt("handle");
		
		return obj;
	}
	
}
