package com.wilutions.jsfs;

/*
 * Serializer for com.wilutions.jsfs.ExecuteNotifyInfo
 * 
 * THIS FILE HAS BEEN GENERATED BY class byps.gen.j.GenSerStructJson DO NOT MODIFY.
 */

import byps.*;

// DEBUG
// isEnum=false
// isFinal=false
// isInline=false
// #members=3

// checkpoint byps.gen.j.GenSerStruct:274
@SuppressWarnings("all")
public class JSerializer_665368294 extends com.wilutions.jsfs.JSerializer_1274131736 {
	
	public final static BSerializer instance = new JSerializer_665368294();
	
	public JSerializer_665368294() {
		super(665368294);
	}
	
	public JSerializer_665368294(int typeId) {
		super(typeId);
	}
	
	
	@Override
	public void internalWrite(final Object obj1, final BOutputJson bout, final BBufferJson bbuf) throws BException {
		final ExecuteNotifyInfo obj = (ExecuteNotifyInfo)obj1;		
		super.internalWrite(obj1, bout, bbuf);		
		bbuf.putInt("exitCode", obj.exitCode);
		bbuf.putString("standardError", obj.standardError);
		bbuf.putString("standardOutput", obj.standardOutput);
	}
	
	@Override
	public Object internalRead(final Object obj1, final BInputJson bin) throws BException {
		final ExecuteNotifyInfo obj = (ExecuteNotifyInfo)(obj1 != null ? obj1 : bin.onObjectCreated(new ExecuteNotifyInfo()));
		
		// Read base class members
		super.internalRead(obj, bin);
		
		final BJsonObject js = bin.currentObject;
		obj.exitCode = js.getInt("exitCode");
		obj.standardError = js.getString("standardError");
		obj.standardOutput = js.getString("standardOutput");
		
		return obj;
	}
	
}
