package com.wilutions.jsfs;

/*
 * Serializer for com.wilutions.jsfs.BRequest_DispatcherService_getNotifyService
 * 
 * THIS FILE HAS BEEN GENERATED BY class byps.gen.j.GenSerStructJson DO NOT MODIFY.
 */

import byps.*;

// DEBUG
// isEnum=false
// isFinal=true
// isInline=false
// #members=2

// checkpoint byps.gen.j.GenSerStruct:274
@SuppressWarnings("all")
public class JSerializer_1090607752 extends JSerializer_Object {
	
	public final static BSerializer instance = new JSerializer_1090607752();
	
	public JSerializer_1090607752() {
		super(1090607752);
	}
	
	public JSerializer_1090607752(int typeId) {
		super(typeId);
	}
	
	
	@Override
	public void internalWrite(final Object obj1, final BOutputJson bout, final BBufferJson bbuf) throws BException {
		final BRequest_DispatcherService_getNotifyService obj = (BRequest_DispatcherService_getNotifyService)obj1;		
		bbuf.putBoolean("onlyHere", obj.onlyHere);
		bbuf.putString("token", obj.token);
	}
	
	@Override
	public Object internalRead(final Object obj1, final BInputJson bin) throws BException {
		final BRequest_DispatcherService_getNotifyService obj = (BRequest_DispatcherService_getNotifyService)(obj1 != null ? obj1 : bin.onObjectCreated(new BRequest_DispatcherService_getNotifyService()));
		
		final BJsonObject js = bin.currentObject;
		obj.onlyHere = js.getBoolean("onlyHere");
		obj.token = js.getString("token");
		
		return obj;
	}
	
}
