package com.wilutions.jsfs;

/*
 * Serializer for com.wilutions.jsfs.BRequest_FileSystemService_executeNotifyExit
 * 
 * THIS FILE HAS BEEN GENERATED BY class byps.gen.j.GenSerStructJson DO NOT MODIFY.
 */

import byps.*;

// DEBUG
// isEnum=false
// isFinal=true
// isInline=false
// #members=2

// checkpoint byps.gen.j.GenSerStruct:274
@SuppressWarnings("all")
public class JSerializer_1824869366 extends JSerializer_Object {
	
	public final static BSerializer instance = new JSerializer_1824869366();
	
	public JSerializer_1824869366() {
		super(1824869366);
	}
	
	public JSerializer_1824869366(int typeId) {
		super(typeId);
	}
	
	
	@Override
	public void internalWrite(final Object obj1, final BOutputJson bout, final BBufferJson bbuf) throws BException {
		final BRequest_FileSystemService_executeNotifyExit obj = (BRequest_FileSystemService_executeNotifyExit)obj1;		
		bout.writeObj("args",obj.args, true, com.wilutions.jsfs.JSerializer_1888107655.instance);
		bout.writeObj("opts",obj.opts, false, null);
	}
	
	@Override
	public Object internalRead(final Object obj1, final BInputJson bin) throws BException {
		final BRequest_FileSystemService_executeNotifyExit obj = (BRequest_FileSystemService_executeNotifyExit)(obj1 != null ? obj1 : bin.onObjectCreated(new BRequest_FileSystemService_executeNotifyExit()));
		
		final BJsonObject js = bin.currentObject;
		obj.args = (java.lang.String[])bin.readObj("args", true, com.wilutions.jsfs.JSerializer_1888107655.instance);
		obj.opts = (com.wilutions.jsfs.ExecuteOptions)bin.readObj("opts", false, null);
		
		return obj;
	}
	
}
