package com.wilutions.jsfs;

/*
 * Serializer for com.wilutions.jsfs.BRequest_FileSystemService_uploadFile
 * 
 * THIS FILE HAS BEEN GENERATED BY class byps.gen.j.GenSerStructJson DO NOT MODIFY.
 */

import byps.*;

// DEBUG
// isEnum=false
// isFinal=true
// isInline=false
// #members=3

// checkpoint byps.gen.j.GenSerStruct:274
@SuppressWarnings("all")
public class JSerializer_744806851 extends JSerializer_Object {
	
	public final static BSerializer instance = new JSerializer_744806851();
	
	public JSerializer_744806851() {
		super(744806851);
	}
	
	public JSerializer_744806851(int typeId) {
		super(typeId);
	}
	
	
	@Override
	public void internalWrite(final Object obj1, final BOutputJson bout, final BBufferJson bbuf) throws BException {
		final BRequest_FileSystemService_uploadFile obj = (BRequest_FileSystemService_uploadFile)obj1;		
		bbuf.putString("method", obj.method);
		bbuf.putString("path", obj.path);
		bbuf.putString("url", obj.url);
	}
	
	@Override
	public Object internalRead(final Object obj1, final BInputJson bin) throws BException {
		final BRequest_FileSystemService_uploadFile obj = (BRequest_FileSystemService_uploadFile)(obj1 != null ? obj1 : bin.onObjectCreated(new BRequest_FileSystemService_uploadFile()));
		
		final BJsonObject js = bin.currentObject;
		obj.method = js.getString("method");
		obj.path = js.getString("path");
		obj.url = js.getString("url");
		
		return obj;
	}
	
}
