package com.wilutions.jsfs;

/*
 * Serializer for com.wilutions.jsfs.BResult_1439246415
 * 
 * THIS FILE HAS BEEN GENERATED BY class byps.gen.j.GenSerStructJson DO NOT MODIFY.
 */

import byps.*;

// DEBUG
// isEnum=false
// isFinal=true
// isInline=false
// #members=1

// checkpoint byps.gen.j.GenSerStruct:274
@SuppressWarnings("all")
public class JSerializer_1733426638 extends JSerializer_Object {
	
	public final static BSerializer instance = new JSerializer_1733426638();
	
	public JSerializer_1733426638() {
		super(1733426638);
	}
	
	public JSerializer_1733426638(int typeId) {
		super(typeId);
	}
	
	
	@Override
	public void internalWrite(final Object obj1, final BOutputJson bout, final BBufferJson bbuf) throws BException {
		final BResult_1439246415 obj = (BResult_1439246415)obj1;		
		bout.writeObj("result",obj.result, false, com.wilutions.jsfs.JSerializer_1439246415.instance);
	}
	
	@Override
	public Object internalRead(final Object obj1, final BInputJson bin) throws BException {
		final BResult_1439246415 obj = (BResult_1439246415)(obj1 != null ? obj1 : bin.onObjectCreated(new BResult_1439246415()));
		
		final BJsonObject js = bin.currentObject;
		obj.result = (java.util.List<com.wilutions.jsfs.FileInfo>)bin.readObj("result", false, com.wilutions.jsfs.JSerializer_1439246415.instance);
		
		return obj;
	}
	
}
